# https://www.chezmoi.io/reference/special-files-and-directories/chezmoiexternal-format/

{{- if eq .chezmoi.os "windows" }}

["Documents/Python/pyreadline3.zip"]
type = "file"
url = "https://files.pythonhosted.org/packages/5a/dc/491b7661614ab97483abf2056be1deee4dc2490ecbf7bff9ab5cdbac86e1/pyreadline3-3.5.4-py3-none-any.whl"
checksum.sha256 = "EAF8E6CC3C49BCCCF145FC6067BA8643D1DF34D604A1EC0ECCBF7A18E6D3FAE6"

["Documents/Privoxy"]
type = "archive"
url = "https://www.privoxy.org/sf-download-mirror/Win32/3.0.34%20%28stable%29/privoxy_3.0.34.zip"
checksum.sha256 = "0E361E54780E292F7A249752471B9C55AF7BD342FD345CD2D0F3EC2BBE7650A4"
stripComponents = 1
exclude = ["*/config.txt", "*/user.action"]

{{- end }}
{{- if ne .chezmoi.uid "0" }}

[".vim/pack/colors/start/gruvbox8"]
type = "archive"
url = "https://github.com/lifepillar/vim-gruvbox8/archive/d1cf31e5215ad6f5544d9e631383aef4b6c35cb7.zip"
checksum.sha256 = "9CB7AA921E4E63147CB954F0383BF9EF681427002EF16FBC5193C91BB8F0FE04"
stripComponents = 1

[".vim/pack/tools/start/vim-commentary"]
type = "archive"
url = "https://github.com/tpope/vim-commentary/archive/c4b8f52cbb7142ec239494e5a2c4a512f92c4d07.zip"
checksum.sha256 = "158980BC79A2622FE543081CC1867C87B6DD8490A9769D8342D003AEFF6E1414"
stripComponents = 1

[".vim/pack/tools/start/scratch.vim"]
type = "archive"
url = "https://github.com/vim-scripts/scratch.vim/archive/90c2bc4bfe01151aa5c71d9cb243b05bc105ae01.zip"
checksum.sha256 = "2A9C78991A04860B876246872A767870B546BF5EF2645CB39DEBE788E334C09E"
stripComponents = 1

[".vim/pack/tools/start/vim-cool"]
type = "archive"
url = "https://github.com/romainl/vim-cool/archive/662e7b11064cbeedad17c45d2fe926e78d3cd0b6.zip"
checksum.sha256 = "30E72316B7CD62459693783496864EE4A4FF7C5BA7AFC47C37951990BDCAE2D6"
stripComponents = 1

[".vim/pack/tools/opt/vim-clang-format"]
type = "archive"
url = "https://github.com/rhysd/vim-clang-format/archive/6b791825ff478061ad1c57b21bb1ed5a5fd0eb29.tar.gz"
checksum.sha256 = "864ff2ede3b5f4f4935c86d2c5082ae80992c433321005940c4d3da8f42b92e9"
stripComponents = 1

{{- end }}
