# https://www.chezmoi.io/reference/special-files-and-directories/chezmoiexternal-format/

{{- if eq .chezmoi.os "windows" }}

["Documents/Python/pyreadline3.zip"]
type = "file"
url = "https://files.pythonhosted.org/packages/5a/dc/491b7661614ab97483abf2056be1deee4dc2490ecbf7bff9ab5cdbac86e1/pyreadline3-3.5.4-py3-none-any.whl"
checksum.sha256 = "EAF8E6CC3C49BCCCF145FC6067BA8643D1DF34D604A1EC0ECCBF7A18E6D3FAE6"

{{- end }}
{{- if ne .chezmoi.uid "0" }}

[".vim/pack/colors/start/gruvbox8"]
type = "archive"
url = "https://github.com/lifepillar/vim-gruvbox8/archive/60bb03df34fd6f22aed9dcb71f5cb297b6cceb3f.zip"
checksum.sha256 = "ED005CBFFD97CA83533D21C49F23682FC29D5B6B4D48F37A74174F3E8B1389CC"
stripComponents = 1

[".vim/pack/tools/start/vim-commentary"]
type = "archive"
url = "https://github.com/tpope/vim-commentary/archive/64a654ef4a20db1727938338310209b6a63f60c9.zip"
checksum.sha256 = "EBDC68C5FBD5742A9E3223B2D5EB73D4C4C6046B7C0D279CC619177C13E914E3"
stripComponents = 1

[".vim/pack/tools/start/scratch.vim"]
type = "archive"
url = "https://github.com/vim-scripts/scratch.vim/archive/90c2bc4bfe01151aa5c71d9cb243b05bc105ae01.zip"
checksum.sha256 = "2A9C78991A04860B876246872A767870B546BF5EF2645CB39DEBE788E334C09E"
stripComponents = 1

[".vim/pack/tools/start/vim-cool"]
type = "archive"
url = "https://github.com/romainl/vim-cool/archive/662e7b11064cbeedad17c45d2fe926e78d3cd0b6.zip"
checksum.sha256 = "30E72316B7CD62459693783496864EE4A4FF7C5BA7AFC47C37951990BDCAE2D6"
stripComponents = 1

[".vim/pack/tools/start/vim-qf"]
type = "archive"
url = "https://github.com/romainl/vim-qf/archive/1dcedfc42c017fd99477bcf36fb1f41e95809800.zip"
checksum.sha256 = "A79D2F50E19FB1060625A48E1FE4F19D795C04CEA6F6D2B21E5D2EF7BE24F7D2"
stripComponents = 1

[".vim/pack/tools/start/vim-fugitive"]
type = "archive"
url = "https://github.com/tpope/vim-fugitive/archive/b068eaf1e6cbe35d1ac100d435cd7f7b74a5c87d.zip"
checksum.sha256 = "D9CEAA3CCCE4F564D0FF62B2CE70FB3F38E25C11AEDB01C09960B707AE8EF070"
stripComponents = 1

[".vim/pack/tools/opt/vim-clang-format"]
type = "archive"
url = "https://github.com/rhysd/vim-clang-format/archive/6b791825ff478061ad1c57b21bb1ed5a5fd0eb29.tar.gz"
checksum.sha256 = "864ff2ede3b5f4f4935c86d2c5082ae80992c433321005940c4d3da8f42b92e9"
stripComponents = 1

{{- end }}
