if has("win32")
  set guifont=IBM_Plex_Mono_Medium:h10:W500:cDEFAULT:qCLEARTYPE
else
  set guifont=Consolas\ 11
endif

set background=light
set guioptions+=!
set guioptions-=L
set guioptions-=T
set guioptions-=m
set guioptions-=r
set t_vb=

if v:servername == 'FAR'
  colorscheme blue
elseif v:servername == 'TCMD'
  colorscheme wildcharm
else
  let g:gruvbox_italicize_strings = 0
  colorscheme gruvbox8
endif

" automatically discard stale buffers from deleted files, based on
" https://stackoverflow.com/a/8851986
augroup auto_wipe_buffers_trick
  autocmd!
  au FocusGained * call functions#WipeBuffersWithoutFiles()
augroup END
