if has("win32")
    set guifont=Consolas:h11
else
    set guifont=Consolas\ 11
endif

set guioptions-=T
set guioptions-=r
set guioptions-=L
set guioptions-=m
set guioptions+=!
set t_vb=

if v:servername == 'FAR'
    colorscheme blue
else
    if strftime('%H') >= 9 && strftime('%H') < 18
        set background=light
    else
        set background=dark
    endif
    colorscheme gruvbox8
endif

" automatically discard stale buffers from deleted files, based on
" https://stackoverflow.com/a/8851986
augroup auto_wipe_buffers_trick
    autocmd!
    au FocusGained * call s:WipeBuffersWithoutFiles()
augroup END
function s:WipeBuffersWithoutFiles()
    let bufs = filter(range(1, bufnr('$')), 'bufexists(v:val) && '.
                \'!bufloaded(v:val) && '.
                \'empty(getbufvar(v:val, "&buftype")) && '.
                \'!filereadable(bufname(v:val))')
    if !empty(bufs)
        execute 'bwipeout' join(bufs)
    endif
endfunction
